fos_message:
    db_driver: orm
    thread_class: Asbo\Bundle\CoreBundle\Entity\Thread
    message_class: Asbo\Bundle\CoreBundle\Entity\Message
    new_thread_form:
      type:               fos_message.new_thread_multiple_form.type
      handler:            fos_message.new_thread_multiple_form.handler
      model:              FOS\MessageBundle\FormModel\NewThreadMultipleMessage
