language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - composer install --prefer-source

script: php bin/phpspec run -f pretty

notifications:
    email: "deronmalian@gmail.com"