language: php

php:
    - 5.4
    - 5.5

before_script:
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - ulimit -n 10000
    - sudo apt-get update
    - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl
    - sudo sed -i -e "s,/var/www,$(pwd)/web,g" /etc/apache2/sites-available/default
    - export MINK_EXTENSION_PARAMS='base_url=http://localhost:8000/app_test.php'
    - sudo /etc/init.d/apache2 restart
    - composer install --prefer-source --no-interaction
    - wget http://getcomposer.org/composer.phar
    - sudo chmod -R 777 app/cache app/logs
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - cp phpspec.yml.dist phpspec.yml

script:
    - cd src/Asbo/Bundle/ContactBundle; ../../../../bin/phpspec run -fpretty --verbose
    - cd ../CoreBundle; ../../../../bin/phpspec run -fpretty --verbose
    - cd ../EventBundle; ../../../../bin/phpspec run -fpretty --verbose
    - cd ../QuizzBundle; ../../../../bin/phpspec run -fpretty --verbose
    - cd ../WhosWhoBundle; ../../../../bin/phpspec run -fpretty --verbose

notifications:
    email: "deronmalian+travis@gmail.com"

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage
