asbo_event:
    driver: doctrine/orm
    classes:
        event:
            model: Asbo\Bundle\CoreBundle\Entity\Event
            controller: Asbo\Bundle\CoreBundle\Controller\EventController

# Timeline
spy_timeline:
    drivers:
        orm:
            object_manager: doctrine.orm.entity_manager
            classes:
                timeline:  Asbo\Bundle\TimelineBundle\Entity\Timeline
                action:    Asbo\Bundle\TimelineBundle\Entity\Action
                component: Asbo\Bundle\TimelineBundle\Entity\Component
                action_component: Asbo\Bundle\TimelineBundle\Entity\ActionComponent

    filters:
        data_hydrator:
            priority:             20
            service:              spy_timeline.filter.data_hydrator
            filter_unresolved:    false
            locators:
                - spy_timeline.filter.data_hydrator.locator.doctrine_orm

    spread:
        on_subject: false

    render:
        path: 'AsboWebBundle:Frontend/Timeline/verbs'
        fallback: 'AsboWebBundle:Frontend/Timeline:default.html.twig'
        resources:
            - 'AsboWebBundle:Frontend/Timeline:components.html.twig'
