AsboWebBundle:
    resource: "@AsboWebBundle/Resources/config/routing/main.yml"
    prefix:   /

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix:   /messages

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix:   /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix:   /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix:   /profile

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix:   /profile

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /oauth/redirect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /oauth/connect

hwi_oauth_connect_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /connect

google_login:
    pattern: /login/check-google

twitter_login:
    pattern: /login/check-twitter

github_login:
    pattern: /login/check-github

facebook_login:
    pattern: /login/check-facebook

linkedin_login:
    pattern: /login/check-linkedin

sonata_media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix:   /media

sonata_gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix:   /media/gallery

sonata_user_admin_security_logout:
    path: /admin/logout

genemu_base64:
    resource: "@GenemuFormBundle/Resources/config/routing/base64.xml"
