#
# This file is part of the ASBO package.
#
# (c) De Ron Malian <deronmalian@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

asbo_calendar:
    prefix: /calendar
    resource: @AsboEventBundle/Resources/config/routing/calendar.yml

asbo_event:
    prefix: /calendar
    resource: @AsboEventBundle/Resources/config/routing/event.yml
