asbo_whoswho_externalpost_delete:
    pattern: /{id}/delete
    methods: [GET, DELETE]
    defaults:
        _controller: asbo_whoswho.controller.externalpost:deleteAction
        _sylius:
            template: AsboWebBundle:Frontend/WhosWho/Fra/ExternalPost:delete.html.twig
            redirect:
                route: asbo_whoswho_fra_show
                parameters: { 'slug': $slug }

asbo_whoswho_externalpost_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: asbo_whoswho.controller.externalpost:createAction
        _sylius:
            template: AsboWebBundle:Frontend/WhosWho/Fra/ExternalPost:create.html.twig
            redirect:
                route: asbo_whoswho_fra_show
                parameters: { 'slug': $slug }

asbo_whoswho_externalpost_update:
    pattern: /{id}
    methods: [GET, POST]
    defaults:
        _controller: asbo_whoswho.controller.externalpost:updateAction
        _sylius:
            template: AsboWebBundle:Frontend/WhosWho/Fra/ExternalPost:update.html.twig
            redirect:
                route: asbo_whoswho_fra_show
                parameters: { 'slug': $slug }
