
asbo_whoswho_frahaspost_delete:
    pattern: /{id}/delete
    methods: [GET, DELETE]
    defaults:
        _controller: asbo_whoswho.controller.frahaspost:deleteAction
        _sylius:
            template: AsboWebBundle:Frontend/WhosWho/Fra/FraHasPost:delete.html.twig
            redirect:
                route: asbo_whoswho_fra_show
                parameters: { 'slug': $slug }

asbo_whoswho_frahaspost_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: asbo_whoswho.controller.frahaspost:createAction
        _sylius:
            template: AsboWebBundle:Frontend/WhosWho/Fra/FraHasPost:create.html.twig
            redirect:
                route: asbo_whoswho_fra_show
                parameters: { 'slug': $slug }

asbo_whoswho_frahaspost_update:
    pattern: /{id}
    methods: [GET, POST]
    defaults:
        _controller: asbo_whoswho.controller.frahaspost:updateAction
        _sylius:
            template: AsboWebBundle:Frontend/WhosWho/Fra/FraHasPost:update.html.twig
            redirect:
                route: asbo_whoswho_fra_show
                parameters: { 'slug': $slug }
