asbo_whoswho_job_delete:
    pattern: /{id}/delete
    methods: [GET, DELETE]
    defaults:
        _controller: asbo_whoswho.controller.job:deleteAction
        _sylius:
            template: AsboWebBundle:Frontend/WhosWho/Fra/Job:delete.html.twig
            redirect:
                route: asbo_whoswho_fra_show
                parameters: { 'slug': $slug }

asbo_whoswho_job_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: asbo_whoswho.controller.job:createAction
        _sylius:
            template: AsboWebBundle:Frontend/WhosWho/Fra/Job:create.html.twig
            redirect:
                route: asbo_whoswho_fra_show
                parameters: { 'slug': $slug }

asbo_whoswho_job_update:
    pattern: /{id}
    methods: [GET, POST]
    defaults:
        _controller: asbo_whoswho.controller.job:updateAction
        _sylius:
            template: AsboWebBundle:Frontend/WhosWho/Fra/Job:update.html.twig
            redirect:
                route: asbo_whoswho_fra_show
                parameters: { 'slug': $slug }
