asbo_whoswho_rank_delete:
    pattern: /{id}/delete
    methods: [GET, DELETE]
    defaults:
        _controller: asbo_whoswho.controller.rank:deleteAction
        _sylius:
            template: AsboWebBundle:Frontend/WhosWho/Fra/Rank:delete.html.twig
            redirect:
                route: asbo_whoswho_fra_show
                parameters: { 'slug': $slug }

asbo_whoswho_rank_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: asbo_whoswho.controller.rank:createAction
        _sylius:
            template: AsboWebBundle:Frontend/WhosWho/Fra/Rank:create.html.twig
            redirect:
                route: asbo_whoswho_fra_show
                parameters: { 'slug': $slug }

asbo_whoswho_rank_update:
    pattern: /{id}
    methods: [GET, POST]
    defaults:
        _controller: asbo_whoswho.controller.rank:updateAction
        _sylius:
            template: AsboWebBundle:Frontend/WhosWho/Fra/Rank:update.html.twig
            redirect:
                route: asbo_whoswho_fra_show
                parameters: { 'slug': $slug }
