asbo_whoswho_api_email_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: asbo_whoswho.controller.email:indexAction
        _format: json

asbo_whoswho_api_email_create:
    pattern: /
    methods: [POST]
    defaults:
        _controller: asbo_whoswho.controller.email:createAction
        _format: json

asbo_whoswho_api_email_update:
    pattern: /{id}
    methods: [PUT]
    defaults:
        _controller: asbo_whoswho.controller.email.updateAction
        _format: json

asbo_whoswho_api_email_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: asbo_whoswho.controller.email.deleteAction
        _format: json

asbo_whoswho_api_email_show:
    pattern: /{id}
    methods: [GET]
    defaults:
        _controller: asbo_whoswho.controller.email.showAction
        _format: json
