parameters:
#    asbo_contact.example.class: Asbo\Bundle\ContactBundle\Example

services:
#    asbo_contact.example:
#        class: %asbo_contact.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
