admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'

_sonata_admin:
    resource: .
    type:     sonata_admin

admin_logout:
    pattern: /logout
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /logout
        permanent: true


asbo_backend_security:
    resource: @AsboWebBundle/Resources/config/routing/backend/security.yml
