# This file is part of the Asbo package.
# (c) De Ron Malian
#
asbo_backend_security_login:
    pattern: /login
    methods: [GET]
    defaults:
        _controller: asbo.controller.backend.security:loginAction

asbo_backend_security_login_check:
    pattern: /login-check
    methods: [POST]
    defaults:
        _controller: asbo.controller.backend.security:checkAction

asbo_backend_security_logout:
    pattern: /logout
    methods: [GET]
    defaults:
        _controller: asbo.controller.backend.security:logoutAction
